## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [16]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import Ridge, Lasso
import numpy as np

In [27]:
##### Wine #####
### red data ###
boston = datasets.load_boston()
X = boston['data']
y = boston['target']

### train test split ###
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2)

### Boston Ridge ###

Ridge1 = Ridge()
alpha = [0.0001, 0.0005,0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.8, 1, 1.5, 2, 2.5,3, 3.5 ,4, 4.5 ,5, 5.5,6, 6.5,7, 7.5 ,8, 8.5,9,9.5,10]
Ridge_score = []
for i in alpha:
    Ridge1.set_params(alpha = i)
    Ridge_score.append([i, cross_val_score(Ridge1, X_train, y_train, cv=5).mean()])
print(np.array(Ridge_score))

##### 發現 alpha 設置 0.1 R^2 最高 #####
Ridge1.set_params(alpha = 0.1)
Ridge1.fit(X_train, y_train)
Ridge1.predict(X_test)
print('Score',Ridge1.score(X_test, y_test))

[[1.00000000e-04 7.19756560e-01]
 [5.00000000e-04 7.19757970e-01]
 [1.00000000e-03 7.19759724e-01]
 [5.00000000e-03 7.19773434e-01]
 [1.00000000e-02 7.19789776e-01]
 [5.00000000e-02 7.19891472e-01]
 [1.00000000e-01 7.19957546e-01]
 [3.00000000e-01 7.19810012e-01]
 [5.00000000e-01 7.19363654e-01]
 [8.00000000e-01 7.18574294e-01]
 [1.00000000e+00 7.18066848e-01]
 [1.50000000e+00 7.16978979e-01]
 [2.00000000e+00 7.16142159e-01]
 [2.50000000e+00 7.15498623e-01]
 [3.00000000e+00 7.14995642e-01]
 [3.50000000e+00 7.14594860e-01]
 [4.00000000e+00 7.14269360e-01]
 [4.50000000e+00 7.14000179e-01]
 [5.00000000e+00 7.13773757e-01]
 [5.50000000e+00 7.13580233e-01]
 [6.00000000e+00 7.13412312e-01]
 [6.50000000e+00 7.13264513e-01]
 [7.00000000e+00 7.13132660e-01]
 [7.50000000e+00 7.13013528e-01]
 [8.00000000e+00 7.12904601e-01]
 [8.50000000e+00 7.12803894e-01]
 [9.00000000e+00 7.12709829e-01]
 [9.50000000e+00 7.12621140e-01]
 [1.00000000e+01 7.12536805e-01]]
Score 0.7081287463542647


In [30]:
### Boston Lasso ###
Lasso1 = Lasso()
alpha = [0, 0.0001, 0.0005,0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.8, 1, 1.5, 2, 2.5,3, 3.5 ,4, 4.5 ,5, 5.5,6, 6.5,7, 7.5 ,8, 8.5,9,9.5,10]
Lasso_score = []
for i in alpha:
    Lasso1.set_params(alpha = i)
    Lasso_score.append([i, cross_val_score(Lasso1, X_train, y_train, cv=5).mean()])
print(np.array(Lasso_score))

##### 發現 alpha 設置 0.001 R^2 最高 #####
Lasso1.set_params(alpha = 0.001)
Lasso1.fit(X_train, y_train)
Lasso1.predict(X_test)
print('Score',Lasso1.score(X_test, y_test))

D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\model_selection\_validation.py:528: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\linear_model\coordinate_descent.py:478: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\model_selection\_validation.py:528: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_tra

[[0.00000000e+00 7.19756207e-01]
 [1.00000000e-04 7.19757763e-01]
 [5.00000000e-04 7.19763079e-01]
 [1.00000000e-03 7.19767664e-01]
 [5.00000000e-03 7.19727989e-01]
 [1.00000000e-02 7.19474301e-01]
 [5.00000000e-02 7.09977133e-01]
 [1.00000000e-01 7.08577459e-01]
 [3.00000000e-01 7.04653207e-01]
 [5.00000000e-01 6.98473660e-01]
 [8.00000000e-01 6.83624991e-01]
 [1.00000000e+00 6.69764195e-01]
 [1.50000000e+00 6.32470763e-01]
 [2.00000000e+00 6.13307366e-01]
 [2.50000000e+00 6.01176206e-01]
 [3.00000000e+00 5.89027131e-01]
 [3.50000000e+00 5.77298779e-01]
 [4.00000000e+00 5.64712442e-01]
 [4.50000000e+00 5.57496788e-01]
 [5.00000000e+00 5.52945883e-01]
 [5.50000000e+00 5.50167276e-01]
 [6.00000000e+00 5.47171198e-01]
 [6.50000000e+00 5.43885223e-01]
 [7.00000000e+00 5.40305663e-01]
 [7.50000000e+00 5.36438016e-01]
 [8.00000000e+00 5.32280332e-01]
 [8.50000000e+00 5.27832578e-01]
 [9.00000000e+00 5.23094789e-01]
 [9.50000000e+00 5.18134073e-01]
 [1.00000000e+01 5.14199693e-01]]
Score 0.7

In [93]:
############# House data ######################
house = datasets.fetch_california_housing()
X = house['data']
y = house['target']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

### Ridge ###
Ridge2 = Ridge()
alpha = [0,0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.8, 1, 1.5, 2, 2.5,3, 3.5 ,4, 4.5 ,5, 5.5,6, 6.5,7, 7.5 ,8, 8.5,9,9.5,10,20,50,100]
Ridge2_score = []
for i in alpha:
    Ridge2.set_params(alpha = i)
    Ridge2_score.append([i, cross_val_score(Ridge2, X_train, y_train, cv=100).mean()])
print(np.array(Ridge2_score))


##### 發現 alpha 設置 100 R^2 最高 #####
Ridge2.set_params(alpha = 100)
Ridge2.fit(X_train, y_train)
Ridge2.predict(X_test)
print('Score',Ridge2.score(X_test, y_test))

[[0.00000000e+00 6.00498636e-01]
 [1.00000000e-03 6.00498651e-01]
 [5.00000000e-03 6.00498710e-01]
 [1.00000000e-02 6.00498783e-01]
 [5.00000000e-02 6.00499372e-01]
 [1.00000000e-01 6.00500108e-01]
 [3.00000000e-01 6.00503046e-01]
 [5.00000000e-01 6.00505977e-01]
 [8.00000000e-01 6.00510359e-01]
 [1.00000000e+00 6.00513271e-01]
 [1.50000000e+00 6.00520518e-01]
 [2.00000000e+00 6.00527718e-01]
 [2.50000000e+00 6.00534873e-01]
 [3.00000000e+00 6.00541981e-01]
 [3.50000000e+00 6.00549044e-01]
 [4.00000000e+00 6.00556061e-01]
 [4.50000000e+00 6.00563033e-01]
 [5.00000000e+00 6.00569960e-01]
 [5.50000000e+00 6.00576843e-01]
 [6.00000000e+00 6.00583680e-01]
 [6.50000000e+00 6.00590473e-01]
 [7.00000000e+00 6.00597222e-01]
 [7.50000000e+00 6.00603927e-01]
 [8.00000000e+00 6.00610589e-01]
 [8.50000000e+00 6.00617207e-01]
 [9.00000000e+00 6.00623782e-01]
 [9.50000000e+00 6.00630313e-01]
 [1.00000000e+01 6.00636802e-01]
 [2.00000000e+01 6.00757911e-01]
 [5.00000000e+01 6.01034273e-01]
 [1.000000

In [90]:
### House Lasso ###
Lasso2= Lasso()
alpha = [0,0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.8, 1, 1.5, 2, 2.5,3, 3.5 ,4, 4.5 ,5, 5.5,6, 6.5,7, 7.5 ,8, 8.5,9,9.5,10,20,50,100]
Lasso2_score = []
for i in alpha:
    Lasso2.set_params(alpha = i)
    Lasso2_score.append([i, cross_val_score(Lasso2, X_train, y_train, cv=5).mean()])
print(np.array(Lasso2_score))

##### 發現 alpha 設置 0.0001R^2 最高 #####
Lasso2.set_params(alpha = 0.0001)
Lasso2.fit(X_train, y_train)
Lasso2.predict(X_test)
print('Score',Lasso2.score(X_test, y_test))
    

D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\model_selection\_validation.py:528: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\linear_model\coordinate_descent.py:478: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
D:\Anaconda3\envs\envirment_1\lib\site-packages\sklearn\model_selection\_validation.py:528: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_tra

[[ 0.00000000e+00  6.03932989e-01]
 [ 1.00000000e-03  6.04095847e-01]
 [ 5.00000000e-03  6.03900710e-01]
 [ 1.00000000e-02  6.01751759e-01]
 [ 5.00000000e-02  5.84518394e-01]
 [ 1.00000000e-01  5.46757950e-01]
 [ 3.00000000e-01  4.92835468e-01]
 [ 5.00000000e-01  4.56344902e-01]
 [ 8.00000000e-01  3.68762740e-01]
 [ 1.00000000e+00  2.87965751e-01]
 [ 1.50000000e+00  1.00013179e-02]
 [ 2.00000000e+00 -4.55472010e-04]
 [ 2.50000000e+00 -4.57006684e-04]
 [ 3.00000000e+00 -4.58837936e-04]
 [ 3.50000000e+00 -4.60965764e-04]
 [ 4.00000000e+00 -4.63390170e-04]
 [ 4.50000000e+00 -4.66111153e-04]
 [ 5.00000000e+00 -4.69128713e-04]
 [ 5.50000000e+00 -4.72442850e-04]
 [ 6.00000000e+00 -4.76053564e-04]
 [ 6.50000000e+00 -4.79960855e-04]
 [ 7.00000000e+00 -4.84164724e-04]
 [ 7.50000000e+00 -4.88665170e-04]
 [ 8.00000000e+00 -4.93462193e-04]
 [ 8.50000000e+00 -4.98555793e-04]
 [ 9.00000000e+00 -5.03945970e-04]
 [ 9.50000000e+00 -5.09632724e-04]
 [ 1.00000000e+01 -5.15616056e-04]
 [ 2.00000000e+01 -6